# 第三节 线性代数与NumPy

### 1. 模块与包

#### 模块：以.py结尾的Python源代码文件
- NumPy
- sys
- time
- ......

#### 包：模块的集合

![](module-package.png)

### 2. NumPy的导入

In [1]:
import numpy as np    # 导入NumPy模块

In [2]:
print(np.version.version)   # 查看当前安装的NumPy的版本

1.19.2


### 3. NumPy的基本数据结构

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])   # NumPy中基本数据类型-数组的声明
print(a)

[[1 2 3]
 [4 5 6]]


In [6]:
print("数组a的维度个数为: ", a.ndim)  # 数组的维度

数组a的维度个数为:  2


In [7]:
print("数组a的各个维度长度为: ", a.shape)  # 数组各个维度的长度

数组a的各个维度长度为:  (2, 3)


In [8]:
print("数组a中元素总数为: ", a.size)  # 数组里元素总数

数组a中元素总数为:  6


In [9]:
print("数组a中元素类型为: ", a.dtype)  # 数组元素的类型

数组a中元素类型为:  int64


In [11]:
b = np.arange(0, 20, 5)     # 用arange函数创建数组 (开始值，终值，步长)
print(b)

[ 0  5 10 15]


In [16]:
b.reshape(2, 2)         # 改变数组的形状

array([[ 0,  5],
       [10, 15]])

In [15]:
c = np.linspace(0, 2, 10)   # 用linspace函数创建数组（开始值，终值，元素个数）
print(c)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [18]:
zero_arr = np.zeros((3,4))   # 快速创建元素全为0的数组
print(zero_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
one_arr = np.ones((2,3,4), dtype=np.int64)   # 快速创建元素全为1的数组，并将类型设置为整型
print(one_arr)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [20]:
eye_arr = np.eye(3)   # 快速创建对角阵 
print(eye_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 4. NumPy数组的切片和索引

In [46]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[0:4])      
print(arr[0:4:2])

[1 2 3 4]
[1 3]


In [47]:
for ele in arr:     # 对数组中每个元素的遍历
    print(ele)

1
2
3
4
5
6


In [34]:
arr = arr.reshape(2,3)     # 更改arr数组的形状
print(arr)

[[1 2 3]
 [4 5 6]]


In [35]:
print(arr[0,:])            # 在arr数组里选择第一维度的第一个子序列，

[1 2 3]


In [36]:
print(arr[0, 0])           # 在arr数组里选择第一维度的第一个子序列里的第一个元素

1


In [37]:
print(arr[:, 1])           # 在arr数组里选择第二维度的第二个子序列里的所有元素

[2 5]


### 5. NumPy数组的基本操作

In [40]:
arr1 = np.array([[1, 2], [3, 4]])     # 声明两个二维数组
print(arr1)
print("********")
arr2 = np.array([[5, 6], [7, 8]])
print(arr2)

[[1 2]
 [3 4]]
********
[[5 6]
 [7 8]]


In [41]:
print(arr2-arr1)     # 两个数组元素级别的差运算

[[4 4]
 [4 4]]


In [42]:
print(arr2+arr1)     # 两个数组元素级别的和运算

[[ 6  8]
 [10 12]]


In [53]:
print(arr2*arr1)     # 两个数组元素级别的乘运算

[[ 5 12]
 [21 32]]


In [54]:
print(arr2/arr1)     # 两个数组元素级别的除运算

[[5.         3.        ]
 [2.33333333 2.        ]]


In [44]:
print(arr1**2)     # 数组元素级别的乘方运算 

[[ 1  4]
 [ 9 16]]


In [48]:
print(arr1@arr2)     # 两个数组之间的矩阵乘积运算

[[19 22]
 [43 50]]


In [52]:
print(np.dot(arr1, arr2))   # 使用dot进行的两个数组之间的矩阵乘积运算
print("*" * 10)
print(arr1.dot(arr2))

[[19 22]
 [43 50]]
**********
[[19 22]
 [43 50]]


In [55]:
print(arr1.T)      # 数组的转置

[[1 3]
 [2 4]]


In [61]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print("arr1中最大元素的索引为: ", np.argmax(arr3))                    # 数组中值最大元素的索引
print("arr1中沿第一个轴最大元素的索引为: ", np.argmax(arr3, axis=0))    # 数组中沿第一个维度值最大元素的索引
print("arr1中沿第二个轴最大元素的索引为: ", np.argmax(arr3, axis=1))    # 数组中沿第二个维度值最大元素的索引

[[1 2 3]
 [4 5 6]]
arr1中最大元素的索引为:  5
arr1中沿第一个轴最大元素的索引为:  [1 1 1]
arr1中沿第二个轴最大元素的索引为:  [2 2]


### 6. NumPy求解线性方程组

In [1]:
# NumPy中array与matrix的异同
import numpy as np
a_arr = np.array([1,2])
print("Array形式的a形状为：", a_arr.shape)
a_mat = np.mat([1,2])
print("Matrix形式的a形状为：", a_mat.shape)

Array形式的a形状为： (2,)
Matrix形式的a形状为： (1, 2)


In [2]:
# 得到矩阵的转置
mat_temp = np.mat([[1,2],[3,4]])
print("此矩阵为：\n", mat_temp)
print('*' * 10)
print("此矩阵的转置为：\n", mat_temp.T)

此矩阵为：
 [[1 2]
 [3 4]]
**********
此矩阵的转置为：
 [[1 3]
 [2 4]]


In [4]:
# 得到矩阵的逆
mat_temp = np.mat([[1,2],[3,4]])
print("此矩阵为：\n", mat_temp)
print('*' * 10)
mat_inv = mat_temp.I
print("此矩阵的逆矩阵为：\n", mat_inv)
print("此矩阵与它的逆矩阵相乘得到：\n", np.round(mat_temp.dot(mat_inv)))    # np.round用来保留结果到指定位数

此矩阵为：
 [[1 2]
 [3 4]]
**********
此矩阵的逆矩阵为：
 [[-2.   1. ]
 [ 1.5 -0.5]]
此矩阵与它的逆矩阵相乘得到：
 [[1. 0.]
 [0. 1.]]


In [5]:
import numpy as np
equa = np.mat([[1,2,3],[4,5,6]])
print("此线性方程组为：\n", equa)
print('*' * 10)
A = np.array([[1,2], [4,5]])   # 2x2系数矩阵
b = np.array([3,6])            # 2x1矩阵
res = np.linalg.solve(A,b)     # 求解该系数矩阵决定的线性方程组
print("此线性方程组的解为：\n", res.reshape(1,2).T)

此线性方程组为：
 [[1 2 3]
 [4 5 6]]
**********
此线性方程组的解为：
 [[-1.]
 [ 2.]]


In [6]:
import numpy as np
equa = np.mat([[1,2,3],[4,5,6]])
print("此线性方程组为：\n", equa)
print('*' * 10)
A = np.mat([[1,2], [4,5]])   # 2x2系数矩阵
b = np.mat([3,6]).T  # 2x1矩阵(须为列向量的形式)
res = np.linalg.solve(A,b)   # 求解该系数矩阵决定的线性方程组
print("此线性方程组的解为：\n", res)

此线性方程组为：
 [[1 2 3]
 [4 5 6]]
**********
此线性方程组的解为：
 [[-1.]
 [ 2.]]
